// This file was generated by the Ruby Statemachine Library (http://slagyr.github.com/statemachine).
// Generated at 15:52:48 March 25, 2010
package limelight.ui.text;

public interface StyledTextStatemachineContext
{
  // Actions
  void alarm();
  void beep();
  void disable();
  void lock();
  void operate();
  void thanks();
  void unlock();
}
